version: '3'

################################################################################################
#
# local dev:
#   - run:
#   - clean:
#
################################################################################################

#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

# env file:
dotenv:
  - .env

################################################################################################


# task groups:
tasks:
  default:
    cmds:
      - task: init
      - task: run

  install:
    cmds:
      - brew install go-task/tap/go-task

  init:
    cmds:
      - cp .env.local .env
      - task: tidy

  tidy:
    cmds:
      - go mod tidy -v



  run-auto:
    cmds:
      - air -d    # auto run

  # exec bin:
  exec:
    cmds:
      - ./tmp/main --chainType=${CHAIN_TYPE} --fromFile=${FROM_FILE} --toFile=${TO_FILE}   # 环境变量传参

  build:
    cmds:
      - go build -o ./tmp/main ./app/cmd

  run:
    cmds:
      - go run ./app/cmd


  #########################################################################


  gen:
    cmds:
      - task: run-auto # auto run


  #########################################################################

  mkdir:
    desc: "create app folder"
    cmds:
      - mkdir -p {{.FOLDER}}


  #########################################################################

  stash:
    cmds:
      - git stash

  quick:
    cmds:
      - task: commit
      - task: pull
      - task: push

  commit:
    cmds:
      - git add lib/
      - git commit -m "update"

  push:
    cmds:
      - git push origin main --tags

  pull:
    cmds:
      - git config pull.rebase false
      - git pull
